language: php

php:
  - 5.6


before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install -r requirements.txt --user `whoami`
  - composer --prefer-source install

script:
  - sphinx-build --version

